hdf5:
- 1.10.6
pandas:
- 1.2.*
python:
- '3.8'
q2_alignment:
- 2021.11.0.dev0
q2_composition:
- 2021.11.0.dev0
q2_cutadapt:
- 2021.11.0.dev0+1.g7130dc1
q2_dada2:
- 2021.11.0.dev0
q2_deblur:
- 2021.11.0.dev0
q2_demux:
- 2021.11.0.dev0
q2_diversity:
- 2021.11.0.dev0
q2_diversity_lib:
- 2021.11.0.dev0
q2_emperor:
- 2021.11.0.dev0
q2_feature_classifier:
- 2021.11.0.dev0
q2_feature_table:
- 2021.11.0.dev0
q2_fragment_insertion:
- 2021.11.0.dev0
q2_gneiss:
- 2021.11.0.dev0
q2_longitudinal:
- 2021.11.0.dev0
q2_metadata:
- 2021.11.0.dev0
q2_mystery_stew:
- 2021.11.0.dev0
q2_phylogeny:
- 2021.11.0.dev0
q2_quality_control:
- 2021.11.0.dev0
q2_quality_filter:
- 2021.11.0.dev0
q2_sample_classifier:
- 2021.11.0.dev0+1.gd6c4a52
q2_taxa:
- 2021.11.0.dev0
q2_types:
- 2021.11.0.dev0+1.g90625f0
q2_vsearch:
- 2021.11.0.dev0
q2cli:
- 2021.11.0.dev0+2.gae2e803
q2galaxy:
- 2021.11.0.dev0
q2templates:
- 2021.11.0.dev0
qiime2:
- 2021.11.0.dev0+1.ge41cb33
qiime2_epoch:
- '2021.11'
scikit_learn:
- 0.24.1
