channels:
- https://packages.qiime2.org/qiime2/2023.12/amplicon/passed/
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.14
- h5py=3.8.0
- hdf5=1.14.0
- matplotlib=3.6.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- patsy=0.5.3
- python=3.8
- q2-alignment=2023.11.0.dev0+1.gf4a4883
- q2-composition=2023.11.0.dev0+2.g89c2a1c
- q2-cutadapt=2023.11.0.dev0+1.g88b8b2a
- q2-dada2=2023.11.0.dev0+1.g0936850
- q2-deblur=2023.11.0.dev0+1.g90f3f43
- q2-demux=2023.11.0.dev0+1.g7539ed6
- q2-diversity-lib=2023.11.0.dev0+1.g0470b71
- q2-diversity=2023.11.0.dev0+1.g2125108
- q2-emperor=2023.11.0.dev0+1.g22ad50e
- q2-feature-classifier=2023.11.0.dev0+1.g787c45f
- q2-feature-table=2023.11.0.dev0+1.ga1b415d
- q2-fragment-insertion=2023.11.0.dev0+1.g5dce83d
- q2-longitudinal=2023.11.0.dev0+2.gd9c4d8d
- q2-metadata=2023.11.0.dev0+1.g5ac3877
- q2-mystery-stew=2023.11.0.dev0+2.g1836c05
- q2-phylogeny=2023.11.0.dev0+1.ge643252
- q2-quality-control=2023.11.0.dev0+1.gae10087
- q2-quality-filter=2023.11.0.dev0+1.g032ad25
- q2-sample-classifier=2023.11.0.dev0+1.gb75a895
- q2-taxa=2023.11.0.dev0+1.g1efb0b0
- q2-types=2023.11.0.dev0+1.g8a0e191
- q2-vsearch=2023.11.0.dev0+2.g693d1c2
- q2cli=2023.11.0.dev0+5.g4819197
- q2galaxy=2023.11.0.dev0+3.ga24b5bc
- q2templates=2023.11.0.dev0
- qiime2=2023.11.0.dev0+5.gcf317be
- r-base=4.2.2
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- seaborn=0.12.2
- unifrac-binaries=1.3.1
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2023.12'
