biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.11.0.dev0+3.g741d22f
q2_assembly:
- 2022.8.0
q2_composition:
- 2022.11.0.dev0+3.g954fb4a
q2_cutadapt:
- 2022.11.0.dev0+3.g376d24e
q2_dada2:
- 2022.11.0.dev0+4.g6f2ffbb
q2_deblur:
- 2022.11.0.dev0+3.gcf69449
q2_demux:
- 2022.11.0.dev0+4.gf17ce91
q2_diversity:
- 2022.11.0.dev0+3.g383cda0
q2_diversity_lib:
- 2022.11.0.dev0+3.g143b937
q2_emperor:
- 2022.11.0.dev0+3.g67ab702
q2_feature_classifier:
- 2022.11.0.dev0+3.ga1396fe
q2_feature_table:
- 2022.11.0.dev0+5.g1b895c0
q2_fmt:
- 2022.11.0.dev0+10.gc8ad59e
q2_fondue:
- 2022.11.0.dev0+5.g3ede75c
q2_fragment_insertion:
- 2022.11.0.dev0+3.gbff184d
q2_gneiss:
- 2022.11.0.dev0+3.geb94ca0
q2_longitudinal:
- 2022.11.0.dev0+3.g3bf9069
q2_metadata:
- 2022.11.0.dev0+3.gd45815e
q2_mystery_stew:
- 2022.11.0.dev0+3.g041e9b4
q2_phylogeny:
- 2022.11.0.dev0+3.g982f5bc
q2_quality_control:
- 2022.11.0.dev0+3.g5e8409e
q2_quality_filter:
- 2022.11.0.dev0+3.ga8b5a7b
q2_sample_classifier:
- 2022.11.0.dev0+3.g27c3de1
q2_stats:
- 2022.11.0.dev0+7.ge4ae41d
q2_taxa:
- 2022.11.0.dev0+3.g8071d5e
q2_types:
- 2022.11.0.dev0+5.g886a1dc
q2_types_genomics:
- 2022.11.0.dev0
q2_vsearch:
- 2022.11.0.dev0+5.ge4885c4
q2cli:
- 2022.11.0.dev0+3.ge3f4c6c
q2galaxy:
- 2022.11.0.dev0+3.g4821f74
q2templates:
- 2022.11.0.dev0+4.g8990a9c
qiime2:
- 2022.11.0.dev0+15.ga0071b5
qiime2_epoch:
- '2022.11'
rescript:
- 2021.11.0+9.gadb941c
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
