biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.11.0.dev0+5.g5d134dc
q2_assembly:
- 2022.11.0.dev0+2.g0fda6d9
q2_checkm:
- 2022.11.0.dev0+1.g55d9e1c
q2_composition:
- 2022.11.0.dev0+3.g954fb4a
q2_cutadapt:
- 2022.11.0.dev0+5.g52a5410
q2_dada2:
- 2022.11.0.dev0+7.gcfa58ef
q2_deblur:
- 2022.11.0.dev0+5.gb64b2a4
q2_demux:
- 2022.11.0.dev0+5.gefe87f8
q2_diversity:
- 2022.11.0.dev0+8.gc59f58e
q2_diversity_lib:
- 2022.11.0.dev0+3.g143b937
q2_emperor:
- 2022.11.0.dev0+6.g9144c4b
q2_feature_classifier:
- 2022.11.0.dev0+3.ga1396fe
q2_feature_table:
- 2022.11.0.dev0+9.gc07624c
q2_fmt:
- 2022.11.0.dev0+10.gc8ad59e
q2_fondue:
- 2022.11.0.dev0+6.g348c59f
q2_fragment_insertion:
- 2022.11.0.dev0+4.g3384472
q2_gneiss:
- 2022.11.0.dev0+3.geb94ca0
q2_longitudinal:
- 2022.11.0.dev0+3.g3bf9069
q2_metadata:
- 2022.11.0.dev0+6.gbac77f4
q2_moshpit:
- 2022.11.0.dev0+1.g24e2030
q2_mystery_stew:
- 2022.11.0.dev0+3.g041e9b4
q2_phylogeny:
- 2022.11.0.dev0+3.g982f5bc
q2_quality_control:
- 2022.11.0.dev0+3.g5e8409e
q2_quality_filter:
- 2022.11.0.dev0+4.g85c16d8
q2_sample_classifier:
- 2022.11.0.dev0+5.gfd205ec
q2_stats:
- 2022.11.0.dev0+9.g80320e5
q2_taxa:
- 2022.11.0.dev0+5.g87a7b4c
q2_types:
- 2022.11.0.dev0+10.gaae4269
q2_types_genomics:
- 2022.11.0.dev0+1.gf9bc552
q2_vsearch:
- 2022.11.0.dev0+5.ge4885c4
q2cli:
- 2022.11.0.dev0+7.g20840ab
q2galaxy:
- 2022.11.0.dev0+3.g4821f74
q2templates:
- 2022.11.0.dev0+5.g2c40e4f
qiime2:
- 2022.11.0.dev0+20.gfe03a82
qiime2_epoch:
- '2022.11'
r_base:
- '>=4.2.0'
rescript:
- 2021.11.0+9.gadb941c
scikit_bio:
- 0.5.8
scikit_learn:
- 0.24.1
scipy:
- '>=1.7'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
