biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.11.0.dev0
q2_assembly:
- 2022.8.0
q2_composition:
- 2022.11.0.dev0+1.g14a2442
q2_cutadapt:
- 2022.11.0.dev0+1.gceff2c8
q2_dada2:
- 2022.11.0.dev0+1.g3612f0a
q2_deblur:
- 2022.11.0.dev0
q2_demux:
- 2022.11.0.dev0+2.g80ee28f
q2_diversity:
- 2022.11.0.dev0
q2_diversity_lib:
- 2022.11.0.dev0
q2_emperor:
- 2022.11.0.dev0
q2_feature_classifier:
- 2022.11.0.dev0+1.gbf759c1
q2_feature_table:
- 2022.11.0.dev0+3.g15c7a28
q2_fmt:
- 2022.11.0.dev0+6.gf456997
q2_fondue:
- 2022.11.0.dev0+4.g0a4582d
q2_fragment_insertion:
- 2022.11.0.dev0
q2_gneiss:
- 2022.11.0.dev0
q2_longitudinal:
- 2022.11.0.dev0
q2_metadata:
- 2022.11.0.dev0
q2_mystery_stew:
- 2022.11.0.dev0
q2_phylogeny:
- 2022.11.0.dev0
q2_quality_control:
- 2022.11.0.dev0
q2_quality_filter:
- 2022.11.0.dev0
q2_sample_classifier:
- 2022.11.0.dev0+1.g9367148
q2_stats:
- 2022.11.0.dev0+5.gd8b34a9
q2_taxa:
- 2022.11.0.dev0+1.gaa75d84
q2_types:
- 2022.11.0.dev0+2.g71c3351
q2_types_genomics:
- 2022.11.0.dev0
q2_vsearch:
- 2022.11.0.dev0+1.g582d776
q2cli:
- 2022.11.0.dev0+1.g0c79319
q2galaxy:
- 2022.11.0.dev0
q2templates:
- 2022.11.0.dev0+2.gd4c9219
qiime2:
- 2022.11.0.dev0+10.g8df50f6
qiime2_epoch:
- '2022.11'
rescript:
- 2021.11.0+9.gadb941c
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
