biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.8.0.dev0
q2_composition:
- 2022.8.0.dev0+1.g93f11c6
q2_cutadapt:
- 2022.8.0.dev0+1.g7c68e38
q2_dada2:
- 2022.8.0.dev0
q2_deblur:
- 2022.8.0.dev0
q2_demux:
- 2022.8.0.dev0+1.geccaa69
q2_diversity:
- 2022.8.0.dev0+1.gf69f653
q2_diversity_lib:
- 2022.8.0.dev0+1.g38ed86e
q2_emperor:
- 2022.8.0.dev0
q2_feature_classifier:
- 2022.8.0.dev0
q2_feature_table:
- 2022.8.0.dev0
q2_fragment_insertion:
- 2022.8.0.dev0
q2_gneiss:
- 2022.8.0.dev0
q2_longitudinal:
- 2022.8.0.dev0+2.g8137822
q2_metadata:
- 2022.8.0.dev0+2.g6a5a1b3
q2_mystery_stew:
- 2022.8.0.dev0
q2_phylogeny:
- 2022.8.0.dev0
q2_quality_control:
- 2022.8.0.dev0
q2_quality_filter:
- 2022.8.0.dev0
q2_sample_classifier:
- 2022.8.0.dev0+1.g29057b8
q2_taxa:
- 2022.8.0.dev0
q2_types:
- 2022.8.0.dev0+1.g6812297
q2_vsearch:
- 2022.8.0.dev0
q2cli:
- 2022.8.0.dev0
q2galaxy:
- 2022.8.0.dev0
q2templates:
- 2022.8.0.dev0
qiime2:
- 2022.8.0.dev0+1.gdf80c3b
qiime2_epoch:
- '2022.8'
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
