biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.11.0.dev0+1.gcd53548
q2_assembly:
- 2022.8.0
q2_composition:
- 2022.11.0.dev0+1.g14a2442
q2_cutadapt:
- 2022.11.0.dev0+2.g5f75c15
q2_dada2:
- 2022.11.0.dev0+3.g0762ca1
q2_deblur:
- 2022.11.0.dev0+1.g383c17d
q2_demux:
- 2022.11.0.dev0+2.g80ee28f
q2_diversity:
- 2022.11.0.dev0+1.g2c6a78b
q2_diversity_lib:
- 2022.11.0.dev0+1.g0e92354
q2_emperor:
- 2022.11.0.dev0+1.g85f7472
q2_feature_classifier:
- 2022.11.0.dev0+1.gbf759c1
q2_feature_table:
- 2022.11.0.dev0+4.g6fc9b30
q2_fmt:
- 2022.11.0.dev0+10.gc8ad59e
q2_fondue:
- 2022.11.0.dev0+5.g3ede75c
q2_fragment_insertion:
- 2022.11.0.dev0+1.g6b7ab31
q2_gneiss:
- 2022.11.0.dev0+1.gb1a5138
q2_longitudinal:
- 2022.11.0.dev0+1.g60dee69
q2_metadata:
- 2022.11.0.dev0+1.g092d181
q2_mystery_stew:
- 2022.11.0.dev0+1.g9e56157
q2_phylogeny:
- 2022.11.0.dev0+2.gf948fbb
q2_quality_control:
- 2022.11.0.dev0+1.g93b9f3c
q2_quality_filter:
- 2022.11.0.dev0+1.gee5efef
q2_sample_classifier:
- 2022.11.0.dev0+1.g9367148
q2_stats:
- 2022.11.0.dev0+6.gf227394
q2_taxa:
- 2022.11.0.dev0+2.g9c6aed0
q2_types:
- 2022.11.0.dev0+3.gce69820
q2_types_genomics:
- 2022.11.0.dev0
q2_vsearch:
- 2022.11.0.dev0+1.g582d776
q2cli:
- 2022.11.0.dev0+2.g1923646
q2galaxy:
- 2022.11.0.dev0+2.g5db223f
q2templates:
- 2022.11.0.dev0+2.gd4c9219
qiime2:
- 2022.11.0.dev0+15.ga0071b5
qiime2_epoch:
- '2022.11'
rescript:
- 2021.11.0+8.ge030fa7
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
