channels:
- https://packages.qiime2.org/qiime2/2024.2/fmt/staged
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.14
- h5py=3.8.0
- hdf5=1.14.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- parsl=2023.12.04
- python=3.8
- q2-fmt=2023.11.0.dev0+7.g22731a9
- q2-mystery-stew=2023.11.0.dev0+2.g1836c05
- q2-stats=2023.11.0.dev0
- q2-types=2023.11.0.dev0+2.g1827eab
- q2-vizard=2023.11.0.dev0
- q2cli=2023.11.0.dev0+12.g7cf7a7a
- qiime2=2023.11.0.dev0+15.g8ac7e3e
- r-base=4.2.2
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- unifrac-binaries=1.3.1
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2023.11'
