biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.4.0.dev0+2.gad02719
q2_assembly:
- 2022.4.0.dev0+7.ge146272
q2_composition:
- 2022.4.0.dev0+2.gc8b20a6
q2_cutadapt:
- 2022.4.0.dev0+2.ga6c7b6a
q2_dada2:
- 2022.4.0.dev0+4.g84f4c78
q2_deblur:
- 2022.4.0.dev0+4.g2bdb02a
q2_demux:
- 2022.4.0.dev0+4.gd3275d7
q2_diversity:
- 2022.4.0.dev0+5.g454f9c1
q2_diversity_lib:
- 2022.4.0.dev0+5.gb6abce9
q2_emperor:
- 2022.4.0.dev0+3.g5cefbf3
q2_feature_classifier:
- 2022.4.0.dev0+4.gac9d8af
q2_feature_table:
- 2022.4.0.dev0+3.gac6c794
q2_fondue:
- 2022.4.0.dev0+5.g8afd9f6.dirty
q2_fragment_insertion:
- 2022.4.0.dev0+2.g46fc22f
q2_gneiss:
- 2022.4.0.dev0+2.g36f5801
q2_longitudinal:
- 2022.4.0.dev0+2.ge77af89
q2_metadata:
- 2022.4.0.dev0+3.gae18b55
q2_moshpit:
- 2022.4.0.dev0+4.ge3c65de
q2_mystery_stew:
- 2022.4.0.dev0
q2_phylogeny:
- 2022.4.0.dev0+5.gbb50d5f
q2_quality_control:
- 2022.4.0.dev0+6.g4bcf507
q2_quality_filter:
- 2022.4.0.dev0+2.g9ae247e
q2_sample_classifier:
- 2022.4.0.dev0+3.gd991f16
q2_stats:
- 0.1.dev0+5.g59666c4
q2_taxa:
- 2022.4.0.dev0+2.g7a46d99
q2_types:
- 2022.4.0.dev0+6.g94fdbff
q2_types_genomics:
- 2022.4.0.dev0
q2_vsearch:
- 2022.4.0.dev0+3.gfb3526f
q2cli:
- 2022.4.0.dev0+1.g851e6a6
q2galaxy:
- 2022.4.0.dev0
q2templates:
- 2022.4.0.dev0+4.ga02455e
qiime2:
- 2022.4.0.dev0+5.g9fae0e7
qiime2_epoch:
- '2022.4'
rescript:
- 2021.11.0+5.ge942be6
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
