biom_format:
- 2.1.12
h5py:
- '>=2.10.0,<3.0a0'
hdf5:
- 1.10.6
numpy:
- 1.23.5
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_types:
- 2023.2.0.dev0
qiime2:
- 2023.2.0.dev0+2.g32040a3
qiime2_epoch:
- '2023.2'
r_base:
- '>=4.2.0'
rescript:
- 2022.8.0+2.g484b37e
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
