biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2022.8.0
q2_assembly:
- 2022.4.0.dev0+9.g828ddec
q2_checkm:
- 0+untagged.5.gcb9fa18
q2_composition:
- 2022.8.0
q2_cutadapt:
- 2022.8.0
q2_dada2:
- 2022.8.0
q2_deblur:
- 2022.8.0
q2_demux:
- 2022.8.0
q2_diversity:
- 2022.8.0
q2_diversity_lib:
- 2022.8.0
q2_emperor:
- 2022.8.0
q2_feature_classifier:
- 2022.8.0
q2_feature_table:
- 2022.8.0
q2_fmt:
- 0.1.dev0+35.ga59f432
q2_fondue:
- 2022.4.0.dev0+12.g5afa120
q2_fragment_insertion:
- 2022.8.0
q2_gneiss:
- 2022.8.0
q2_longitudinal:
- 2022.8.0
q2_metadata:
- 2022.8.0
q2_mystery_stew:
- 2022.8.0
q2_phylogeny:
- 2022.8.0
q2_quality_control:
- 2022.8.0
q2_quality_filter:
- 2022.8.0
q2_sample_classifier:
- 2022.8.0
q2_stats:
- 2022.8.0.dev0+1.gbde8c96
q2_taxa:
- 2022.8.0
q2_types:
- 2022.8.0
q2_types_genomics:
- 2022.8.0.dev0
q2_vsearch:
- 2022.8.0
q2cli:
- 2022.8.0
q2galaxy:
- 2022.8.1
q2templates:
- 2022.8.0
qiime2:
- 2022.8.1
qiime2_epoch:
- '2022.8'
rescript:
- 2021.11.0+7.g0a7c822
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
