channels:
  - https://packages.qiime2.org/qiime2/2023.2/staged/core
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - q2-alignment=2023.2.0.dev0
  - q2-composition=2023.2.0.dev0
  - q2-cutadapt=2023.2.0.dev0
  - q2-dada2=2023.2.0.dev0
  - q2-deblur=2023.2.0.dev0
  - q2-demux=2023.2.0.dev0+1.g069b5af
  - q2-diversity=2023.2.0.dev0+1.gbb6d045
  - q2-diversity-lib=2023.2.0.dev0
  - q2-emperor=2023.2.0.dev0+1.gc79b39a
  - q2-feature-classifier=2023.2.0.dev0
  - q2-feature-table=2023.2.0.dev0+1
  - q2-fragment-insertion=2023.2.0.dev0
  - q2-gneiss=2023.2.0.dev0
  - q2-longitudinal=2023.2.0.dev0
  - q2-metadata=2023.2.0.dev0+1.g9a3f2cb
  - q2-mystery-stew=2023.2.0.dev0
  - q2-phylogeny=2023.2.0.dev0
  - q2-quality-control=2023.2.0.dev0
  - q2-quality-filter=2023.2.0.dev0
  - q2-sample-classifier=2023.2.0.dev0
  - q2-taxa=2023.2.0.dev0+1.g730cd5d
  - q2-types=2023.2.0.dev0
  - q2-vsearch=2023.2.0.dev0
  - q2cli=2023.2.0.dev0
  - q2galaxy=2023.2.0.dev0
  - q2templates=2023.2.0.dev0
  - qiime2=2023.2.0.dev0+2.g32040a3
  - biom-format=2.1.12
  - h5py=2.10.0
  - hdf5=1.10.6
  - numpy=1.23.5
  - pandas=1.5.3
  - python=3.8
  - scikit-bio=0.5.7
  - scikit-learn=0.24.1
  - scipy=1.8.1
  - unifrac=1.1.1
  - unifrac-binaries=1.1.1
  - r-base=4.2.2
extras:
  variant_override:
    # This MUST be a string, lest the YAML dragon eat October
    qiime2_epoch: '2023.2'

