hdf5:
- 1.10.6
pandas:
- 1.2.*
python:
- 3.8
q2_composition:
- 2021.10.0.dev0
q2_dada2:
- 2021.10.0.dev0
q2_mystery_stew:
- 2021.10.0.dev0
q2_types:
- 2021.10.0.dev0
q2cli:
- 2021.10.0.dev0
q2templates:
- 2021.10.0.dev0
qiime2:
- 2021.10.0.dev0
qiime2_epoch:
- '2021.10'
