biom_format:
- '>=2.1.12'
hdf5:
- '*'
pandas:
- '>=1.2.5'
python:
- '3.8'
q2_alignment:
- 2023.2.0.dev0
q2_composition:
- 2023.2.0.dev0+30.g311505a
q2_cutadapt:
- 2023.2.0.dev0
q2_dada2:
- 2023.2.0.dev0
q2_deblur:
- 2023.2.0.dev0
q2_demux:
- 2023.2.0.dev0+1.g069b5af
q2_diversity:
- 2023.2.0.dev0+1.gbb6d045
q2_diversity_lib:
- 2023.2.0.dev0
q2_emperor:
- 2023.2.0.dev0+1.gc79b39a
q2_feature_classifier:
- 2023.2.0.dev0
q2_feature_table:
- 2023.2.0.dev0+1.gecdd7ce
q2_fmt:
- 2023.2.0.dev0+66.g08d5dcc
q2_fragment_insertion:
- 2023.2.0.dev0
q2_gneiss:
- 2023.2.0.dev0
q2_longitudinal:
- 2023.2.0.dev0
q2_metadata:
- 2023.2.0.dev0+2.g61fd0e9
q2_mystery_stew:
- 2023.2.0.dev0
q2_phylogeny:
- 2023.2.0.dev0
q2_quality_control:
- 2023.2.0.dev0
q2_quality_filter:
- 2023.2.0.dev0
q2_sample_classifier:
- 2023.2.0.dev0
q2_stats:
- 2023.2.0.dev0+3.g470fd7d
q2_taxa:
- 2023.2.0.dev0+1.g730cd5d
q2_types:
- 2023.2.0.dev0+1.gd3afb6c
q2_vsearch:
- 2023.2.0.dev0
q2cli:
- 2023.2.0.dev0
q2galaxy:
- 2023.2.0.dev0
q2templates:
- 2023.2.0.dev0
qiime2:
- 2023.2.0.dev0+3.g43a8324
qiime2_epoch:
- '2023.2'
r_base:
- '>=4.2.0'
rescript:
- 2021.11.0+9.gadb941c
scikit_bio:
- 0.5.7
scikit_learn:
- 0.24.1
scipy:
- '>=1.7,<1.9'
unifrac:
- 1.1.1
unifrac_binaries:
- 1.1.1
