hdf5:
- 1.10.6
pandas:
- 1.2.*
python:
- 3.8
q2_alignment:
- 2021.8.0.dev0+4.g978b7d5
q2_composition:
- 2021.8.0.dev0+5.g5193056
q2_cutadapt:
- 2021.8.0.dev0+4.g66c3f5c
q2_dada2:
- 2021.8.0.dev0+7.ge7dd0b7
q2_deblur:
- 2021.8.0.dev0+5.g974b409
q2_demux:
- 2021.8.0.dev0+4.g9a0570d
q2_diversity:
- 2021.8.0.dev0+5.g7381575
q2_diversity_lib:
- 2021.8.0.dev0+5.g4a3476f
q2_emperor:
- 2021.8.0.dev0+4.g6ea0507
q2_feature_classifier:
- 2021.8.0.dev0+4.g180d869
q2_feature_table:
- 2021.8.0.dev0+6.g9ba0e7b
q2_fragment_insertion:
- 2021.8.0.dev0+4.g788899b
q2_gneiss:
- 2021.8.0.dev0+4.g31807e2
q2_longitudinal:
- 2021.8.0.dev0+5.gc8e817b
q2_metadata:
- 2021.8.0.dev0+4.gcb61c53
q2_mystery_stew:
- 2021.8.0.dev0+4.ga7c672d
q2_phylogeny:
- 2021.8.0.dev0+7.g0f5b9ce
q2_quality_control:
- 2021.8.0.dev0+4.gbc8eb92
q2_quality_filter:
- 2021.8.0.dev0+4.gae8dba5
q2_sample_classifier:
- 2021.8.0.dev0+6.g2afc45f
q2_taxa:
- 2021.8.0.dev0+5.g833b935
q2_types:
- 2021.8.0.dev0+7.gc0efaa0
q2_vsearch:
- 2021.8.0.dev0+6.g5e7919f
q2cli:
- 2021.8.0.dev0+7.gca76eea
q2templates:
- 2021.8.0.dev0+3.gd744b4d
qiime2:
- 2021.8.0.dev0+9.g1858eef
qiime2_epoch:
- 2021.8
