hdf5:
- 1.10.6
python:
- 3.8
q2_alignment:
- 2021.8.0.dev0+3.gca6330e
q2_composition:
- 2021.8.0.dev0+4.g2345bd8
q2_cutadapt:
- 2021.8.0.dev0+3.g9905731
q2_dada2:
- 2021.8.0.dev0+6.g2564c58
q2_deblur:
- 2021.8.0.dev0+4.g5808d97
q2_demux:
- 2021.8.0.dev0+3.gbc3c5cf
q2_diversity_lib:
- 2021.8.0.dev0+4.g59456f9
q2_emperor:
- 2021.8.0.dev0+3.g0657213
q2_feature_table:
- 2021.8.0.dev0+4.g7856273
q2_gneiss:
- 2021.8.0.dev0+3.gc785ad9
q2_metadata:
- 2021.8.0.dev0+3.g0c444b1
q2_mystery_stew:
- 2021.8.0.dev0+3.g3a86a07
q2_quality_control:
- 2021.8.0.dev0+3.g59f53bd
q2_quality_filter:
- 2021.8.0.dev0+3.ge6ddf6b
q2_sample_classifier:
- 2021.8.0.dev0+5.gdbbbdda
q2_taxa:
- 2021.8.0.dev0+3.gf15c6d1
q2_types:
- 2021.8.0.dev0+3.gcd1e2e1
q2_vsearch:
- 2021.8.0.dev0+5.g898b812
q2cli:
- 2021.8.0.dev0+6.g568b8a2
q2templates:
- 2021.8.0.dev0+3.gd744b4d
qiime2:
- 2021.8.0.dev0+8.g8c82f7d
