channels:
- https://packages.qiime2.org/qiime2/2023.7/core/passed
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.14
- h5py=3.8.0
- hdf5=1.14.0
- notebook=6.5.5
- numpy=1.24.4
- pandas=1.5.3
- python=3.8
- q2-mystery-stew=2023.9.0.dev0+2.g2b4de72
- q2-stats=2023.9.0.dev0
- q2-types=2023.9.0.dev0+1.gd297c53
- q2-vizard=2023.7.0
- q2cli=2023.9.0.dev0+2.gbdc69e4
- qiime2=2023.9.0.dev0+5.gc7a842e
- r-base=4.2.2
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- unifrac-binaries=1.3.1
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2023.9'
