channels:
- https://packages.qiime2.org/qiime2/2024.10/tiny/passed
- conda-forge
- bioconda
dependencies:
- biom-format=2.1.15
- h5py=3.11.0
- hdf5=1.14.3
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- python=3.10
- q2-metadata=2024.10.0.dev0
- q2-mystery-stew=2024.10.0.dev0
- q2-types=2024.10.0.dev0+23.g4b9509a
- q2cli=2024.10.0.dev0+5.g76b8d1e
- q2templates=2024.10.0.dev0
- qiime2=2024.10.0.dev0+17.g5fb10c4
- r-base=4.3.3
- r-reticulate=1.36.0
- scikit-bio=0.6.0
- scikit-learn=1.4.2
- scipy=1.13.0
- unifrac-binaries=1.4
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2024.10'
# modified: 2024-10-13
