channels:
- https://packages.qiime2.org/qiime2/2024.10/amplicon/passed
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.15
- h5py=3.11.0
- hdf5=1.14.3
- mafft=7.520
- matplotlib=3.8.4
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- patsy=0.5.6
- pillow=10.3.0
- python=3.9.19
- python_abi=3.9
- q2-alignment=2024.10.0.dev0
- q2-composition=2024.10.0.dev0
- q2-cutadapt=2024.10.0.dev0
- q2-dada2=2024.10.0.dev0
- q2-deblur=2024.10.0.dev0
- q2-demux=2024.10.0.dev0
- q2-diversity-lib=2024.10.0.dev0
- q2-diversity=2024.10.0.dev0
- q2-emperor=2024.10.0.dev0
- q2-feature-classifier=2024.10.0.dev0
- q2-feature-table=2024.10.0.dev0
- q2-fragment-insertion=2024.10.0.dev0
- q2-longitudinal=2024.10.0.dev0
- q2-metadata=2024.10.0.dev0
- q2-mystery-stew=2024.10.0.dev0
- q2-phylogeny=2024.10.0.dev0
- q2-quality-control=2024.10.0.dev0
- q2-quality-filter=2024.10.0.dev0
- q2-sample-classifier=2024.10.0.dev0
- q2-taxa=2024.10.0.dev0
- q2-types=2024.10.0.dev0
- q2-vsearch=2024.10.0.dev0
- q2cli=2024.10.0.dev0
- q2galaxy=2024.10.0.dev0
- q2templates=2024.10.0.dev0
- qiime2=2024.10.0.dev0
- r-base=4.3.3
- r-reticulate=1.36.0
- rescript=2024.10.0.dev0+2.gd112353
- scikit-bio=0.6.0
- scikit-learn=1.4.2
- scipy=1.13.0
- seaborn=0.12.2
- unifrac-binaries=1.4
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2024.10'
