channels:
- https://packages.qiime2.org/qiime2/2023.7/core/passed
- conda-forge
- bioconda
- defaults
dependencies:
- q2-alignment=2023.7.0
- q2-composition=2023.7.0
- q2-cutadapt=2023.7.0
- q2-dada2=2023.7.0
- q2-deblur=2023.7.0
- q2-demux=2023.7.0
- q2-diversity=2023.7.0
- q2-diversity-lib=2023.7.0
- q2-emperor=2023.7.0
- q2-feature-classifier=2023.7.0
- q2-feature-table=2023.7.0
- q2-fragment-insertion=2023.7.0
- q2-gneiss=2023.7.0
- q2-longitudinal=2023.7.0
- q2-metadata=2023.7.0
- q2-mystery-stew=2023.7.0
- q2-phylogeny=2023.7.0
- q2-quality-control=2023.7.0
- q2-quality-filter=2023.7.0
- q2-sample-classifier=2023.7.0
- q2-taxa=2023.7.0
- q2-types=2023.7.0
- q2-vsearch=2023.7.0
- q2cli=2023.7.0
- q2galaxy=2023.7.0
- q2templates=2023.7.0
- qiime2=2023.7.0
- biom-format=2.1.14
- h5py=3.8.0
- hdf5=1.14.0
- numpy=1.24.4
- pandas=1.5.3
- python=3.8
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.0
- unifrac=1.3
- unifrac-binaries=1.3.1
- r-base=4.2.2
- provenance-lib=2023.7.1
- notebook=7.0.2
extras:
  variant_override:
    qiime2_epoch: '2023.7'
