channels:
- https://packages.qiime2.org/qiime2/2023.7/core/passed
- conda-forge
- bioconda
- defaults
dependencies:
- q2-alignment=2023.7.0.dev0+1.gb74f1ad
- q2-composition=2023.7.0.dev0+4.gb2c8733
- q2-cutadapt=2023.7.0.dev0+1.gdb6d44b
- q2-dada2=2023.7.0.dev0+1.gc3061d3
- q2-deblur=2023.7.0.dev0+2.g23bbd4b
- q2-demux=2023.7.0.dev0+1.g3a591ef
- q2-diversity=2023.7.0.dev0+2.g71d3d14
- q2-diversity-lib=2023.7.0.dev0+1.gbfc7996
- q2-emperor=2023.7.0.dev0+1.g415e661
- q2-feature-classifier=2023.7.0.dev0+1.g7f2729a
- q2-feature-table=2023.7.0.dev0+3.gee964ac
- q2-fragment-insertion=2023.7.0.dev0+1.gc97bdae
- q2-gneiss=2023.7.0.dev0+1.gdc02780
- q2-longitudinal=2023.7.0.dev0+1.g291d35a
- q2-metadata=2023.7.0.dev0+3.ga2b085b
- q2-mystery-stew=2023.7.0.dev0+2.g2d3ac47
- q2-phylogeny=2023.7.0.dev0+1.gaf1c7ca
- q2-quality-control=2023.7.0.dev0+1.gc61d1b3
- q2-quality-filter=2023.7.0.dev0+1.g4c455a9
- q2-sample-classifier=2023.7.0.dev0+1.g4d31f48
- q2-taxa=2023.7.0.dev0+1.g9027f39
- q2-types=2023.7.0.dev0+3.gb8de86d
- q2-vsearch=2023.7.0.dev0+1.gbd10860
- q2cli=2023.7.0.dev0+3.ge342f43
- q2galaxy=2023.7.0.dev0
- q2templates=2023.7.0.dev0+1.gd73abfc
- qiime2=2023.7.0.dev0+12.gb7a1766
- biom-format=2.1.15
- h5py=3.9.0
- hdf5=1.14.1
- numpy=1.24.4
- pandas=1.5.3
- python=3.8
- scikit-bio=0.5.8
- scikit-learn=0.24.1
- scipy=1.10.1
- unifrac=1.3
- unifrac-binaries=1.3.1
- r-base=4.2.2
extras:
  variant_override:
    qiime2_epoch: '2023.7'
