biom_format:
- '>=2.1.7,<2.1.12'
hdf5:
- '*'
pandas:
- 1.2.*
python:
- '3.8'
q2_alignment:
- 2022.4.0.dev0+1.g47021f3
q2_assembly:
- 2022.4.0.dev0+3.gd88013e.dirty
q2_composition:
- 2022.4.0.dev0+1.g7843f0a
q2_cutadapt:
- 2022.4.0.dev0+1.g5e6a984
q2_dada2:
- 2022.4.0.dev0+2.g617d41d
q2_deblur:
- 2022.4.0.dev0+1.gf4b5fb0
q2_demux:
- 2022.4.0.dev0+3.g200e91b
q2_diversity:
- 2022.4.0.dev0+4.g1c0d9e3
q2_diversity_lib:
- 2022.4.0.dev0+3.g6347cff
q2_emperor:
- 2022.4.0.dev0+1.gfe04904
q2_feature_classifier:
- 2022.4.0.dev0+1.g81836c5
q2_feature_table:
- 2022.4.0.dev0+1.g5128da6
q2_fmt:
- 0.1.dev0+30.gc3bd2bd
q2_fondue:
- 2022.4.0.dev0+3.gfa38d26.dirty
q2_fragment_insertion:
- 2022.4.0.dev0+1.g90258f5
q2_gneiss:
- 2022.4.0.dev0+1.g6353a1e
q2_longitudinal:
- 2022.4.0.dev0+1.gdea62f5
q2_metadata:
- 2022.4.0.dev0+1.g43b32d0
q2_moshpit:
- 2022.4.0.dev0+3.ge2b8e67.dirty
q2_mystery_stew:
- 2022.4.0.dev0
q2_phylogeny:
- 2022.4.0.dev0+2.g6d70e3d
q2_quality_control:
- 2022.4.0.dev0+3.g27d62e9
q2_quality_filter:
- 2022.4.0.dev0+1.gcae1001
q2_sample_classifier:
- 2022.4.0.dev0+1.ge7fb6c6
q2_stats:
- 0.1.dev0
q2_taxa:
- 2022.4.0.dev0+1.gaa0749a
q2_types:
- 2022.4.0.dev0+3.g7933ef1
q2_types_genomics:
- 2022.4.0.dev0
q2_vsearch:
- 2022.4.0.dev0+1.g7185730
q2cli:
- 2022.4.0.dev0+1.g851e6a6
q2galaxy:
- 2022.4.0.dev0
q2templates:
- 2022.4.0.dev0+3.ge173fd9
qiime2:
- 2022.4.0.dev0+4.g34f918f
qiime2_epoch:
- '2022.4'
rescript:
- 2021.11.0+3.g8aa880e
scikit_bio:
- 0.5.6
scikit_learn:
- 0.24.1
unifrac:
- '*'
