hdf5:
- '*'
pandas:
- 1.2.*
python:
- '3.8'
q2_alignment:
- 2022.2.0
q2_composition:
- 2022.2.0
q2_cutadapt:
- 2022.2.0
q2_dada2:
- 2022.2.0.dev0+3.gad2fe49
q2_deblur:
- 2022.2.0.dev0+1.g3547583
q2_demux:
- 2022.2.0.dev0+2.g85c68a3
q2_diversity:
- 2022.2.0.dev0+3.g67621a4
q2_diversity_lib:
- 2022.2.0
q2_emperor:
- 2022.2.0
q2_feature_classifier:
- 2022.2.0.dev0+1.gec0436f
q2_feature_table:
- 2022.2.0
q2_fragment_insertion:
- 2022.2.0.dev0+1.g10207fb
q2_gneiss:
- 2022.2.0.dev0+1.g1addb7d
q2_longitudinal:
- 2022.2.0.dev0+2.g639ced8
q2_metadata:
- 2022.2.0
q2_mystery_stew:
- 2022.2.0
q2_phylogeny:
- 2022.2.0.dev0+1.g9b43909
q2_quality_control:
- 2022.2.0
q2_quality_filter:
- 2022.2.0.dev0+1.gbc6e71d
q2_sample_classifier:
- 2022.2.0.dev0+2.g91fcdd2
q2_taxa:
- 2022.2.0
q2_types:
- 2022.2.0
q2_vsearch:
- 2022.2.0.dev0+1.g7ca48b8
q2cli:
- 2022.2.0.dev0+7.gaee8a15
q2galaxy:
- 2022.2.0.dev0+5.g17e2768
q2templates:
- 2022.2.0
qiime2:
- 2022.2.0
qiime2_epoch:
- '2022.2'
rescript:
- 2021.11.0+1.ge73ade0
scikit_learn:
- 0.24.1
unifrac:
- '*'
