channels:
- https://packages.qiime2.org/qiime2/2024.5/tiny/staged
- conda-forge
- bioconda
- defaults
dependencies:
- biom-format=2.1.15
- h5py=3.11.0
- hdf5=1.14.3
- notebook=6.5.5
- numpy=1.26.4
- pandas=2.2.2
- parsl=2024.4.15
- python=3.9.19
- python_abi=3.9
- q2-mystery-stew=2024.5.0
- q2-types=2024.5.0
- q2cli=2024.5.0
- qiime2=2024.5.0
- r-base=4.3.3
- r-reticulate=1.36.0
- scikit-bio=0.6.0
- scikit-learn=1.4.2
- scipy=1.13.0
- unifrac-binaries=1.4
- unifrac=1.3
extras:
  variant_override:
    qiime2_epoch: '2024.5'
